project:
  type: website

website:
  title: "Catherine Blatter"
  site-url: https://cathblatter.netlify.app
  navbar:
    title: "Catherine Blatter"
    right:
      - href: index.qmd
        text: home
      # - href: about/
      #   text: about
      - href: listings.qmd
        text: posts
      - icon: github
        href: https://github.com/cathblatter
      - icon: mastodon
        href: https://fosstodon.org/@cathblatter

format:
  html:
    theme: 
      - cosmo
      - custom.scss
    css: styles.css
    toc: true

execute:
  freeze: auto
  
from: markdown+emoji