project:
  type: website

website:
  title: "Cath Blatter"
  site-url: https://cathblatter.ch
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: listings.html
        text: Posts

format:
  html:
    theme: solar
    css: styles.css
    toc: true

execute:
  freeze: auto