project:
  type: website

website:
  title: "Cath Blatter"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: listings.html
        text: Posts

format:
  html:
    theme: [solar, custom.scss]
    css: styles.css
    toc: true

execute:
  freeze: auto